package com.aiad;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Health implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.lang.Boolean isHighRiskPatient;
    private java.lang.Boolean isMediumRiskPatient;
    private java.lang.Boolean isLowRiskPatient;
    private java.lang.Boolean ageBigger25;
    private java.lang.Boolean ageBetween25and60;
    private java.lang.Boolean ageBigger60;
    private java.lang.Boolean isObese;
    private java.lang.Boolean isAnorexic;
    private int price;

    public Health() {
    }

    public java.lang.Boolean getIsHighRiskPatient() {
        return this.isHighRiskPatient;
    }

    public void setIsHighRiskPatient(java.lang.Boolean isHighRiskPatient) {
        this.isHighRiskPatient = isHighRiskPatient;
    }

    public java.lang.Boolean getIsMediumRiskPatient() {
        return this.isMediumRiskPatient;
    }

    public void setIsMediumRiskPatient(java.lang.Boolean isMediumRiskPatient) {
        this.isMediumRiskPatient = isMediumRiskPatient;
    }

    public java.lang.Boolean getIsLowRiskPatient() {
        return this.isLowRiskPatient;
    }

    public void setIsLowRiskPatient(java.lang.Boolean isLowRiskPatient) {
        this.isLowRiskPatient = isLowRiskPatient;
    }

    public java.lang.Boolean getAgeBigger25() {
        return this.ageBigger25;
    }

    public void setAgeBigger25(java.lang.Boolean ageBigger25) {
        this.ageBigger25 = ageBigger25;
    }

    public java.lang.Boolean getAgeBetween25and60() {
        return this.ageBetween25and60;
    }

    public void setAgeBetween25and60(java.lang.Boolean ageBetween25and60) {
        this.ageBetween25and60 = ageBetween25and60;
    }

    public java.lang.Boolean getAgeBigger60() {
        return this.ageBigger60;
    }

    public void setAgeBigger60(java.lang.Boolean ageBigger60) {
        this.ageBigger60 = ageBigger60;
    }

    public java.lang.Boolean getIsObese() {
        return this.isObese;
    }

    public void setIsObese(java.lang.Boolean isObese) {
        this.isObese = isObese;
    }

    public java.lang.Boolean getIsAnorexic() {
        return this.isAnorexic;
    }

    public void setIsAnorexic(java.lang.Boolean isAnorexic) {
        this.isAnorexic = isAnorexic;
    }

    public int getPrice() {
        return this.price;
    }

    public void setPrice(int price) {
        this.price = price;
    }

    public Health(java.lang.Boolean isHighRiskPatient,
                  java.lang.Boolean isMediumRiskPatient,
                  java.lang.Boolean isLowRiskPatient, java.lang.Boolean ageBigger25,
                  java.lang.Boolean ageBetween25and60, java.lang.Boolean ageBigger60,
                  java.lang.Boolean isObese, java.lang.Boolean isAnorexic, int price) {
        this.isHighRiskPatient = isHighRiskPatient;
        this.isMediumRiskPatient = isMediumRiskPatient;
        this.isLowRiskPatient = isLowRiskPatient;
        this.ageBigger25 = ageBigger25;
        this.ageBetween25and60 = ageBetween25and60;
        this.ageBigger60 = ageBigger60;
        this.isObese = isObese;
        this.isAnorexic = isAnorexic;
        this.price = price;
    }

}